AllCops:
  NewCops: enable
Gemspec/RequiredRubyVersion:
  Enabled: false
Layout/LineLength:
  Max: 120
Layout/MultilineMethodCallIndentation:
  Exclude:
    - ./spec/**/*_spec.rb
Metrics/BlockLength:
  Exclude:
    - ./spec/**/*_spec.rb
Metrics/MethodLength:
  Max: 20
Style/GuardClause:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
